# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: RealtimeBargainingAPI CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x 

    - name: Restore dependencies
      run: dotnet restore source/RealtimeBargainingAPI/RealtimeBargainingAPI.csproj

    - name: Build the project
      run: dotnet build source/RealtimeBargainingAPI/RealtimeBargainingAPI.csproj --configuration Release --no-restore
